"""Run curated CSSOM / DOM conformance checks through the JS interpreter.

The point is not to reimplement Web Platform Tests, but to have a small,
readable battery of spec assertions -- ``el.style`` / ``CSSStyleDeclaration``,
``classList``, ``dataset``, attributes -- that runs end to end through
``domonic_libs.acorn.interpret`` against a live domonic DOM, so regressions and
missing behaviour in domonic surface as a falling score rather than silently.

``run_suite()`` returns a :class:`SuiteResult`; ``format_markdown()`` renders the
scorecard written to ``docs/conformance.md``; ``tests/test_conformance.py`` gates
the totals against :data:`BASELINE`.
"""

from __future__ import annotations

import dataclasses
from pathlib import Path

from domonic_libs.acorn.interpret import Interpreter, JSThrow, default_globals

from .harness import HARNESS_JS

SUITE_DIR = Path(__file__).parent / "suite"

# Lowest pass counts we accept per file -- CI fails if any file regresses below
# its baseline. Raise these as domonic improves; never lower them silently.
BASELINE = {
    "cssom-shorthand.js": 0,        # domonic stores shorthands verbatim (no longhand expansion)
    "cssom-style-declaration.js": 12,
    "dom-attributes.js": 8,         # no getAttributeNames; attr names not lower-cased
    "dom-classlist.js": 14,
    "dom-dataset.js": 7,
}


@dataclasses.dataclass
class Case:
    name: str
    status: str  # "PASS" | "FAIL"
    message: str


@dataclasses.dataclass
class FileResult:
    filename: str
    cases: list[Case]
    error: str = ""  # set when the file blew up before any case ran

    @property
    def passed(self) -> int:
        return sum(c.status == "PASS" for c in self.cases)

    @property
    def total(self) -> int:
        return len(self.cases)


@dataclasses.dataclass
class SuiteResult:
    files: list[FileResult]

    @property
    def passed(self) -> int:
        return sum(f.passed for f in self.files)

    @property
    def total(self) -> int:
        return sum(f.total for f in self.files)

    @property
    def failures(self) -> list[tuple[str, Case]]:
        return [(f.filename, c) for f in self.files for c in f.cases if c.status == "FAIL"]


def _run_file(path: Path) -> FileResult:
    g, console, document, window = default_globals()
    interp = Interpreter(g, global_object=window)
    src = HARNESS_JS + "\n// ---- test file ----\n" + path.read_text()
    try:
        interp.run(src)
    except JSThrow as exc:
        return FileResult(path.name, [], error=str(exc))
    except Exception as exc:  # noqa: BLE001 - any interpreter failure is a suite failure
        return FileResult(path.name, [], error=f"{type(exc).__name__}: {exc}")
    raw = interp.global_env.get("__results")
    cases = [Case(str(r.get("name")), str(r.get("status")), str(r.get("message", ""))) for r in raw]
    return FileResult(path.name, cases)


def run_suite(suite_dir: Path | None = None) -> SuiteResult:
    d = suite_dir or SUITE_DIR
    return SuiteResult([_run_file(p) for p in sorted(d.glob("*.js"))])


def format_markdown(result: SuiteResult) -> str:
    lines = [
        "# CSSOM / DOM conformance scorecard",
        "",
        "Generated by `python -m domonic_libs.conformance`. Each row runs a curated",
        "`.js` file of spec assertions through the tree-walking interpreter in",
        "`domonic_libs.acorn.interpret` against a live domonic DOM. A failing row",
        "is a domonic (or interpreter) gap -- see `docs/domonic-wrinkles.md`.",
        "",
        f"**Total: {result.passed} / {result.total} assertions pass.**",
        "",
        "| File | Pass | Total | Notes |",
        "| --- | --- | --- | --- |",
    ]
    for f in result.files:
        note = f"error: {f.error}" if f.error else ("all pass" if f.passed == f.total else f"{f.total - f.passed} failing")
        lines.append(f"| `{f.filename}` | {f.passed} | {f.total} | {note} |")
    fails = result.failures
    if fails:
        lines += ["", "## Failing assertions", ""]
        for filename, case in fails:
            lines.append(f"- **{filename}** — {case.name}: {case.message}")
    lines.append("")
    return "\n".join(lines)


def main(argv=None) -> int:
    result = run_suite()
    out = Path(__file__).resolve().parents[3] / "docs" / "conformance.md"
    if out.parent.is_dir():
        out.write_text(format_markdown(result))
        print(f"wrote {out}")
    print(f"{result.passed}/{result.total} assertions pass")
    for filename, case in result.failures:
        print(f"  FAIL {filename}: {case.name} -- {case.message}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
