"""A curated test262-style battery run through the JS interpreter.

This is not a vendored copy of test262 (that suite is ~50k files); it is a
hand-written battery modelled on test262's assertions, covering the areas that
exercise ``domonic.javascript`` and the ``domonic_libs.acorn`` interpreter:
language expressions and statements, and the ``Array`` / ``String`` / ``Object``
/ ``Number`` / ``Math`` / ``JSON`` / ``Promise`` / ``RegExp`` built-ins.

``run_suite()`` returns a :class:`SuiteResult`; ``format_markdown`` renders the
scorecard written to ``docs/js-compliance.md``; ``tests/test_js262.py`` gates the
per-file pass counts against :data:`BASELINE`. A failing check is a gap in the
interpreter or in domonic -- the message says which, and the two wrinkle docs
track the domonic ones.
"""

from __future__ import annotations

import dataclasses
from pathlib import Path

from domonic_libs.acorn.interpret import Interpreter, JSThrow, default_globals

from .harness import HARNESS_JS

SUITE_DIR = Path(__file__).parent / "suite"

# Lowest per-file pass counts CI accepts. Raise these as the interpreter and
# domonic improve; never lower one silently.
BASELINE = {
    "array.js": 20,
    "classes.js": 12,
    "coercion.js": 16,
    "expressions.js": 17,
    "functions.js": 15,
    "json.js": 10,
    "number-math.js": 12,
    "object.js": 14,
    "promise-async.js": 13,
    "regexp.js": 15,
    "statements.js": 16,
    "string.js": 15,
}


@dataclasses.dataclass
class Case:
    name: str
    status: str
    message: str


@dataclasses.dataclass
class FileResult:
    filename: str
    cases: list[Case]
    error: str = ""

    @property
    def passed(self) -> int:
        return sum(c.status == "PASS" for c in self.cases)

    @property
    def total(self) -> int:
        return len(self.cases)


@dataclasses.dataclass
class SuiteResult:
    files: list[FileResult]

    @property
    def passed(self) -> int:
        return sum(f.passed for f in self.files)

    @property
    def total(self) -> int:
        return sum(f.total for f in self.files)

    @property
    def failures(self) -> list[tuple[str, Case]]:
        return [(f.filename, c) for f in self.files for c in f.cases if c.status == "FAIL"]


def _run_file(path: Path) -> FileResult:
    g, _console, _document, window = default_globals()
    interp = Interpreter(g, global_object=window)
    src = HARNESS_JS + "\n// ---- " + path.name + " ----\n" + path.read_text()
    try:
        interp.run(src)
    except JSThrow as exc:
        return FileResult(path.name, [], error=str(exc))
    except Exception as exc:  # noqa: BLE001
        return FileResult(path.name, [], error=f"{type(exc).__name__}: {exc}")
    raw = interp.global_env.get("$RESULTS")
    cases = [Case(str(r.get("name")), str(r.get("status")), str(r.get("message", ""))) for r in raw]
    return FileResult(path.name, cases)


def run_suite(suite_dir: Path | None = None) -> SuiteResult:
    d = suite_dir or SUITE_DIR
    return SuiteResult([_run_file(p) for p in sorted(d.glob("*.js"))])


def format_markdown(result: SuiteResult) -> str:
    pct = (100 * result.passed / result.total) if result.total else 0
    lines = [
        "# JavaScript compliance scorecard",
        "",
        "Generated by `python -m domonic_libs.js262`. A curated test262-style battery",
        "run through `domonic_libs.acorn.interpret` against `domonic.javascript`. It is",
        "the objective signal for how close the JS layer is to spec -- a failing check",
        "is an interpreter gap or a domonic gap (the message says which; the wrinkle",
        "docs track the domonic ones).",
        "",
        f"**{result.passed} / {result.total} checks pass ({pct:.0f}%).**",
        "",
        "| File | Pass | Total | |",
        "| --- | --- | --- | --- |",
    ]
    for f in result.files:
        bar = "█" * round(10 * f.passed / f.total) + "░" * (10 - round(10 * f.passed / f.total)) if f.total else ""
        note = f"error: {f.error}" if f.error else bar
        lines.append(f"| `{f.filename}` | {f.passed} | {f.total} | {note} |")
    fails = result.failures
    if fails:
        lines += ["", f"## Failing checks ({len(fails)})", ""]
        for filename, case in fails:
            lines.append(f"- **{filename}** — {case.name}: {case.message}")
    lines.append("")
    return "\n".join(lines)


def main(argv=None) -> int:
    result = run_suite()
    out = Path(__file__).resolve().parents[3] / "docs" / "js-compliance.md"
    if out.parent.is_dir():
        out.write_text(format_markdown(result))
        print(f"wrote {out}")
    print(f"{result.passed}/{result.total} checks pass "
          f"({100 * result.passed / result.total:.0f}%)" if result.total else "no checks")
    for filename, case in result.failures:
        print(f"  FAIL {filename}: {case.name} -- {case.message}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
